#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jedi
Version  : 0.14.0
Release  : 31
URL      : https://files.pythonhosted.org/packages/eb/3b/300fd8107e30f7b957a1dc1ef7f67cd382802aaf6be361022f039d95c130/jedi-0.14.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/eb/3b/300fd8107e30f7b957a1dc1ef7f67cd382802aaf6be361022f039d95c130/jedi-0.14.0.tar.gz
Summary  : An autocompletion tool for Python that can be used for text editors.
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: jedi-license = %{version}-%{release}
Requires: jedi-python = %{version}-%{release}
Requires: jedi-python3 = %{version}-%{release}
Requires: parso
BuildRequires : buildreq-distutils3
BuildRequires : parso
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
###################################################################
Jedi - an awesome autocompletion/static analysis library for Python
###################################################################

%package license
Summary: license components for the jedi package.
Group: Default

%description license
license components for the jedi package.


%package python
Summary: python components for the jedi package.
Group: Default
Requires: jedi-python3 = %{version}-%{release}

%description python
python components for the jedi package.


%package python3
Summary: python3 components for the jedi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jedi package.


%prep
%setup -q -n jedi-0.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561086510
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jedi
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/jedi/LICENSE.txt
cp docs/_themes/flask/LICENSE %{buildroot}/usr/share/package-licenses/jedi/docs__themes_flask_LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jedi/LICENSE.txt
/usr/share/package-licenses/jedi/docs__themes_flask_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
