#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jedi
Version  : 0.13.1
Release  : 25
URL      : https://files.pythonhosted.org/packages/c1/fd/cba30adcd2a739b1288b9dc87830c28797181492757080294523d03599e6/jedi-0.13.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c1/fd/cba30adcd2a739b1288b9dc87830c28797181492757080294523d03599e6/jedi-0.13.1.tar.gz
Summary  : An autocompletion tool for Python that can be used for text editors.
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: jedi-python3
Requires: jedi-license
Requires: jedi-python
Requires: colorama
Requires: parso
Requires: pytest
BuildRequires : buildreq-distutils3
BuildRequires : parso
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
Jedi - an awesome autocompletion/static analysis library for Python
        ###################################################################

%package license
Summary: license components for the jedi package.
Group: Default

%description license
license components for the jedi package.


%package python
Summary: python components for the jedi package.
Group: Default
Requires: jedi-python3 = %{version}-%{release}

%description python
python components for the jedi package.


%package python3
Summary: python3 components for the jedi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jedi package.


%prep
%setup -q -n jedi-0.13.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538595319
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/jedi
cp LICENSE.txt %{buildroot}/usr/share/doc/jedi/LICENSE.txt
cp docs/_themes/flask/LICENSE %{buildroot}/usr/share/doc/jedi/docs__themes_flask_LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/jedi/LICENSE.txt
/usr/share/doc/jedi/docs__themes_flask_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
